---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1496746/public_html/simaci
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R Modules $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH